package finalproject;


import finalproject.Crud1;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Final_proj extends javax.swing.JFrame {

    DefaultTableModel table;
    
    /**
     * Creates new form Final_proj
     */
    public Final_proj() {
        initComponents();
        table = (DefaultTableModel) jTable1.getModel();
        this.setBounds(124,160,1128,405);
    }

    
    
    
    void Print_Data() {
        
        finalproject.Crud1.init();
        
        Connection c =  finalproject.Crud1.getConnection();
        table.setRowCount(0);
        try {
            PreparedStatement ps = c.prepareStatement("SELECT * FROM hospital_data");
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
                table.addRow(new Object[]{rs.getString("ID"), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5),  rs.getString(6), rs.getString(7)});
            }            
        } catch (SQLException ex) {
            Logger.getLogger(Final_proj.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }    
   
    void Save_Data() {
        
        try {
        finalproject.Crud1.init();
        
        Connection c =  finalproject.Crud1.getConnection();
        
        
            PreparedStatement ps = c.prepareStatement("Insert into hospital_data (ID,Patient_name,Patient_illness,Days_admitted,Payment,Insurance_company,Insurance_recieved) values('" + 0 + "','" + Pname.getText() + "','" + Pillnes.getText() + "','" + Pdays.getText() + "','" + Ppayment.getText() + "','" + PInsurancecomp.getText() + "','" + PInsurancerec.getText() + "')");
           
            ps.execute();
                
            JOptionPane.showMessageDialog(this, "Data Successfully Saved");
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Final_proj.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    void Clear(){
        
        Pname.setText("");
        Pillnes.setText("");
        Pdays.setText("");
        Ppayment.setText("");
        PInsurancecomp.setText("");
        PInsurancerec.setText("");
        
        
    }
    void Close(){
        
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Pname = new javax.swing.JTextField();
        Pillnes = new javax.swing.JTextField();
        Pdays = new javax.swing.JTextField();
        Ppayment = new javax.swing.JTextField();
        PInsurancecomp = new javax.swing.JTextField();
        PInsurancerec = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 270));

        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 730, 350));

        jLabel1.setText("Patient Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel4.setText("Patient Illness:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel5.setText("No. of days admitted:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel6.setText("Payment:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel7.setText("Insurance Company:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 20));

        jLabel8.setText("Insurance Amount Recieved:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        Pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PnameActionPerformed(evt);
            }
        });
        jPanel1.add(Pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 160, 30));

        Pillnes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PillnesActionPerformed(evt);
            }
        });
        jPanel1.add(Pillnes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 160, 30));

        Pdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PdaysActionPerformed(evt);
            }
        });
        jPanel1.add(Pdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 160, 30));

        Ppayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PpaymentActionPerformed(evt);
            }
        });
        jPanel1.add(Ppayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 160, 30));

        PInsurancecomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PInsurancecompActionPerformed(evt);
            }
        });
        jPanel1.add(PInsurancecomp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 160, 30));

        PInsurancerec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PInsurancerecActionPerformed(evt);
            }
        });
        jPanel1.add(PInsurancerec, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 160, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Patient Name", "Patient Illness", "Days Admitted", "Payment", "Insurance Company", "Insurance Recieved"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 710, 330));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 80, -1));

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 80, -1));

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PnameActionPerformed

    private void PillnesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PillnesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PillnesActionPerformed

    private void PdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PdaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PdaysActionPerformed

    private void PpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PpaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PpaymentActionPerformed

    private void PInsurancecompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PInsurancecompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PInsurancecompActionPerformed

    private void PInsurancerecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PInsurancerecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PInsurancerecActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Save_Data();
        Clear();
        Print_Data();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Clear();
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Final_proj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Final_proj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Final_proj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Final_proj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Final_proj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PInsurancecomp;
    private javax.swing.JTextField PInsurancerec;
    private javax.swing.JTextField Pdays;
    private javax.swing.JTextField Pillnes;
    private javax.swing.JTextField Pname;
    private javax.swing.JTextField Ppayment;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
